### PR TITLE
Support null safety

### PR DESCRIPTION
**Pull request by rlazom**
This will solve issue #57

### CODE REVIEW

**Comment by leynier** [comment]
@justsoft please 🙏🏻 review this PR, we need null safety support.

**Comment by prateekmedia** [comment]
Errors when compiling :

```css
video_thumbnail/lib/video_thumbnail.dart:38:17: Warning: Operand of null-aware operation '?.' has type 'ImageFormat' which excludes null.
 - 'ImageFormat' is from 'package:video_thumbnail/video_thumbnail.dart' ('video_thumbnail/lib/video_thumbnail.dart').
      'format': imageFormat?.index ?? 0,
                ^
video_thumbnail/lib/video_thumbnail.dart:39:15: Warning: Operand of null-aware operation '??' has type 'int' which excludes null.
      'maxh': maxHeight ?? 0,
              ^

video_thumbnail/lib/video_thumbnail.dart:40:15: Warning: Operand of null-aware operation '??' has type 'int' which excludes null.
      'maxw': maxWidth ?? 0,
              ^
video_thumbnail/lib/video_thumbnail.dart:41:17: Warning: Operand of null-aware operation '??' has type 'int' which excludes null.

      'timeMs': timeMs ?? 0,
                ^
video_thumbnail/lib/video_thumbnail.dart:42:18: Warning: Operand of null-aware operation '??' has type 'int' which excludes null.

      'quality': quality ?? 10
                 ^
video_thumbnail/lib/video_thumbnail.dart:61:17: Warning: Operand of null-aware operation '?.' has type 'ImageFormat' which excludes null.
 - 'ImageFormat' is from 'package:video_thumbnail/video_thumbnail.dart' ('video_thumbnail/lib/video_thumbnail.dart').
      'format': imageFormat?.index ?? 0,
                ^
video_thumbnail/lib/video_thumbnail.dart:62:15: Warning: Operand of null-aware operation '??' has type 'int' which excludes null.
      'maxh': maxHeight ?? 0,
              ^
video_thumbnail/lib/video_thumbnail.dart:63:15: Warning: Operand of null-aware operation '??' has type 'int' which excludes null.
      'maxw': maxWidth ?? 0,
              ^
video_thumbnail/lib/video_thumbnail.dart:64:17: Warning: Operand of null-aware operation '??' has type 'int' which excludes null.
      'timeMs': timeMs ?? 0,
                ^
video_thumbnail/lib/video_thumbnail.dart:65:18: Warning: Operand of null-aware operation '??' has type 'int' which excludes null.
      'quality': quality ?? 10
                 ^
```

**Review by justsoft — APPROVED** [review]

**Comment by prateekmedia** [comment]
@justsoft could you checkout the above errors occured when compiling.

**Comment by justsoft** [comment]
@prateekmedia Fixed, please upgrade to 0.3.1.

**Pull request merged**
