### PR TITLE
Fix: IOException on runtime

### PR DESCRIPTION
**Pull request by ajbcoder**
Fix for #119 and #121

### CODE REVIEW

**Review by dmytrohurskyi — APPROVED** [review]

**Comment by dmytrohurskyi** [comment]
@justsoft could you merge this PR? library needs to support Android SDK 33

**Comment by rlee1990** [comment]
@justsoft can you please merge or add someone as an admin so this can be merged? Other packages rely on this and won't update without this.

**Comment by AgentRachithHegde** [comment]
Can you please merge the fix, I am able to resolve the issue after adding the fix in the respective file.

**Comment by justsoft** [comment]
Sorry, I am busy on other project.
Thank you for your contributions!

**Pull request merged**
