### PR TITLE
Migrate to flutter embedding v2 for Android

### PR DESCRIPTION
**Pull request by wangbo4020**
Migrate to flutter embedding v2 for Android

### CODE REVIEW

**Comment by wangbo4020** [comment]
#45

**Review by justsoft — COMMENTED** [review]
Current is 0: (OPTION_PREVIOUS_SYNC), it is `This option is used with getFrameAtTime(long, int) to retrieve a sync (or key) frame associated with a data source that is located right before or at the given time.`
What will return if the given time exceeded the video length?

**Comment by justsoft** [comment]
I would like to hold the v2 change, right now Flutter only complains the v1.
Also your diffs seem have unnecessary changes.

**Comment by thedude61636** [comment]
in the native android method call, you're using timeMs as an integer it should be changed to a long
more than 32 bits of dart integer will automatically be translated to a long in java which will crash during casting to int

**Comment by justsoft** [comment]
> in the native android method call, you're using timeMs as an integer it should be changed to a long
> more than 32 bits of dart integer will automatically be translated to a long in java which will crash during casting to int

Thanks, will do.

**Comment by sgehrman** [comment]
The plugin `video_thumbnail` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

**Comment by wangbo4020** [comment]
temporary:
```yaml

  video_thumbnail:
    git: 
      url: git@github.com:wangbo4020/video_thumbnail.git
```

> The plugin `video_thumbnail` uses a deprecated version of the Android embedding.
> To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
> If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

**Comment by justsoft** [comment]
Thank you guys!

**Pull request merged**
