### PR TITLE
Generate the thumbnail asynchronously on Android.

### PR DESCRIPTION
**Pull request by tairrzayev-chi**
Fixes frame drops by moving the I/O-intensive work off the UI thread in the Android native code.

### CODE REVIEW

**Comment by plavreshin** [comment]
👍 Thanks @tairrzayev-chi , would highly appreciate that being merged further!

**Comment by JEuler** [comment]
Yeah, would be cool!

**Comment by justsoft** [comment]
Thanks, sorry for vacation delay, I will check your change soon.

**Comment by JEuler** [comment]
Will you release it on https://pub.dev/packages/video_thumbnail ? :)

**Comment by justsoft** [comment]
Looks like there’s something wrong while flutter pub publish, it stuck couple times. I will try it another time.

Regards
-John

**Pull request merged**
